name: CIntegration

on: [push]

jobs:
  sast_scan:
    name: Run Bandit Scan
    runs-on: ubtuntu-;atest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install Bandit
      run: pip install bandit

    - name: Run bandit scan
      run: bandit -r .
